# -*- coding: utf-8 -*-
"""Chest X-Ray Images (Pneumonia).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11W2PMzp8iY-n9PZaT1gNx_dsHzWhX3hL

**Task 1 – Data Understanding**

Load dataset using ImageDataGenerator

**Print:**

Number of training images

Number of validation images

Display 5 sample X-ray images
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense ,Dropout
from keras.utils import to_categorical
import matplotlib.pyplot as plt
import numpy as np

import kagglehub

# Download latest version
path = kagglehub.dataset_download("paultimothymooney/chest-xray-pneumonia")

print("Path to dataset files:", path)

train_dir = path + "/chest_xray/train"
val_dir = path + "/chest_xray/val"

train_datagen = ImageDataGenerator(
    rescale=1./255
)

val_datagen = ImageDataGenerator(
    rescale=1./255
)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(150,150),
    batch_size=32,
    class_mode='binary',
    color_mode='grayscale'
)

validation_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=(150,150),
    batch_size=32,
    class_mode='binary',
    color_mode='grayscale'
)

print("Number of training images:", train_generator.samples)

print("Number of validation images:", validation_generator.samples)

images, labels = next(train_generator)

plt.figure(figsize=(10,6))

for i in range(5):
    plt.subplot(1,5,i+1)
    plt.imshow(images[i])
    plt.title("Label: " + ("PNEUMONIA" if labels[i]==1 else "NORMAL"))
    plt.axis("off")

plt.show()

"""Task 2 – Build CNN Architecture
Students must design this architecture:
Input (150x150x1)
↓
Conv2D (32 filters, 3x3) + ReLU
↓
MaxPooling (2x2)
↓
Conv2D (64 filters, 3x3) + ReLU
↓
MaxPooling (2x2)
↓
Conv2D (128 filters, 3x3) + ReLU
↓
MaxPooling (2x2)
↓
Flatten
↓
Dense (128) + ReLU
↓
Dropout (0.5)
"""

model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 1)),
    MaxPooling2D((2, 2)),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D((2, 2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')
])
# Display the model summary
model.summary()

# Compile the model
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# Train the model
history = model.fit(
    train_generator,
    epochs=5,
    validation_data=validation_generator
)

"""Task 4 – Evaluation"""

from sklearn.metrics import confusion_matrix

# predictions
pred_probs = model.predict(validation_generator)
pred_labels = (pred_probs > 0.5).astype(int)

# actual labels
true_labels = validation_generator.classes

cm = confusion_matrix(true_labels, pred_labels)

print("Confusion Matrix:")
print(cm)

from sklearn.metrics import classification_report

print("Classification Report:\n")
print(classification_report(true_labels, pred_labels,target_names=["NORMAL","PNEUMONIA"]))

class_labels = ["NORMAL","PNEUMONIA"]

images, labels = next(validation_generator)

predictions = model.predict(images)

for i in range(5):

    plt.imshow(images[i].reshape(150,150), cmap='gray')
    plt.axis("off")

    actual = class_labels[int(labels[i])]
    pred = class_labels[int(predictions[i] > 0.5)]
    prob = predictions[i][0]

    plt.title(f"Actual: {actual}\nPredicted: {pred}\nProbability: {prob:.2f}")
    plt.show()
